name: CI/CD

on:
  push:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ctrl-human-${{ github.sha }}
          path: src/
          if-no-files-found: error
          include-hidden-files: true

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: ctrl-human-${{ github.sha }}
          path: src/

      - name: Copy Files to Server
        uses: Dylan700/sftp-upload-action@latest
        with:
          server: ${{ secrets.SSH_ADRESS }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          uploads: |
            src/ => /httpdocs/